title: "slama.dev"
description: "Tom's personal website."

url: "https://slama.dev/"
wiki-url: "https://wiki.slama.dev/"
baseurl: ""

color-theme: "light"

markdown: kramdown

# exclude Jekyll-related files and scripts
exclude: ["Gemfile", "Gemfile.lock", "scripts/", "README.md", "s-theme.gemspec"]
