title: "slama.dev"
description: "Tomáš Sláma's personal website."
url: "https://slama.dev"

baseurl: ""
markdown: kramdown

# exclude Jekyll-related files, scripts and generated content
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "s-theme.gemspec",
  "ignored/",
  "scripts/",
  "raw/",
  "makefile",
  "_wiki/private",
  "_wiki/diary",
  "LICENSE.txt",
  "README.md",
]

collections:
  wiki:
    output: true

defaults:
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:slugified_categories/:title/
