title: "slama.dev"
description: "Tom's personal website."

baseurl: ""
url: "https://slama.dev/"

dark-theme: false

markdown: kramdown

# exclude Jekyll-related files and scripts
exclude: ["Gemfile", "Gemfile.lock", "scripts/", "README.md", "s-theme.gemspec"]
