title: "slama.dev"
description: "Tomáš Sláma's personal website."

url: "https://slama.dev"
baseurl: ""

markdown: kramdown

# exclude Jekyll-related files and scripts
exclude: ["Gemfile", "Gemfile.lock", "scripts/", "README.md", "s-theme.gemspec", "LICENSE.txt"]

# exclude sourcemaps in production
sass:
  sourcemap: never
