# title and decription of the webpage
title: "slama.dev"
description: "Tom's personal website."

baseurl: ""  # base url of all pages (/blog/...)
url: ""      # url of the webpage (www.something.com)

dark-theme: false  # whether to use the dark theme or not

markdown: kramdown
